name: 24f2006529@ds.study.iitm.ac.in

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 24f2006529@ds.study.iitm.ac.in
      run: echo "Hello, world!"
      
